TIMEOUT_REFRESH_CURRENT_ACTIVITY = 1500;
CURRENT_ACTIVITY_NOT_SET_VALUE = -9999;
MAX_ATTEMPS_STATUS_UPDATE = 15;
DELAY_BETWEEN_ATTEMPS_STATUS_UPDATE = 2000;
DELAY_TO_UPDATE_STATUS = 800;
DELAY_LAUNCH_REFRESH = 2500;
DELAY_BEFORE_RECONNECT = 1500;

module.exports = {
  TIMEOUT_REFRESH_CURRENT_ACTIVITY,
  CURRENT_ACTIVITY_NOT_SET_VALUE,
  MAX_ATTEMPS_STATUS_UPDATE,
  DELAY_BETWEEN_ATTEMPS_STATUS_UPDATE,
  DELAY_TO_UPDATE_STATUS,
  DELAY_LAUNCH_REFRESH,
  DELAY_BEFORE_RECONNECT,
};
