TIMEOUT_REFRESH_CURRENT_ACTIVITY = 1500;
CURRENT_ACTIVITY_NOT_SET_VALUE = -9999;
MAX_ATTEMPS_STATUS_UPDATE = 15;
DELAY_BETWEEN_ATTEMPS_STATUS_UPDATE = 2000;
DELAY_TO_UPDATE_STATUS = 500;
DELAY_LAUNCH_REFRESH = 2500;
DELAY_BEFORE_RECONNECT = 10000;
DELAY_FOR_STATELESS_SWITCH_UPDATE = 350;
DELAY_FOR_SLIDER_UPDATE = 500;
DELAY_FOR_MACRO = 350;
DEVICE_TYPE = 'DEVICE';
ACTIVITY_TYPE = 'ACTVIVITY';
DEVICEMACRO_TYPE = 'DEVICEMACRO';
HOME_TYPE = 'HOME';
SEQUENCE_TYPE = 'SEQUENCE';
GENERALMUTE_TYPE = 'MUTE';
GENERALVOLUME_TYPE = 'VOLUME';
GENERALVOLUMEUP_TYPE = 'VOLUMEUP';
GENERALVOLUMEDOWN_TYPE = 'VOLUMEDOWN';
DEFAULT_VOLUME = 50;
HUB_CONNECT_TIMEOUT = 10000;
HUB_SEND_TIMEOUT = 30000;
MAX_SOCKET_ERROR = 5;
DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS = 60000;
DELAY_FOR_AUTO_DISCOVERY = 6000;

module.exports = {
  TIMEOUT_REFRESH_CURRENT_ACTIVITY,
  CURRENT_ACTIVITY_NOT_SET_VALUE,
  MAX_ATTEMPS_STATUS_UPDATE,
  DELAY_BETWEEN_ATTEMPS_STATUS_UPDATE,
  DELAY_TO_UPDATE_STATUS,
  DELAY_LAUNCH_REFRESH,
  DELAY_BEFORE_RECONNECT,
  DELAY_FOR_STATELESS_SWITCH_UPDATE,
  DELAY_FOR_SLIDER_UPDATE,
  DELAY_FOR_MACRO,
  DEVICE_TYPE,
  ACTIVITY_TYPE,
  DEVICEMACRO_TYPE,
  HOME_TYPE,
  SEQUENCE_TYPE,
  GENERALMUTE_TYPE,
  GENERALVOLUME_TYPE,
  GENERALVOLUMEUP_TYPE,
  GENERALVOLUMEDOWN_TYPE,
  DEFAULT_VOLUME,
  HUB_CONNECT_TIMEOUT,
  HUB_SEND_TIMEOUT,
  MAX_SOCKET_ERROR,
  DELAY_BEFORE_RETRY_AFTER_NETWORK_LOSS,
  DELAY_FOR_AUTO_DISCOVERY,
};
