DEFAULT_HUB_PORT = '8088';
TIMEOUT_REFRESH_CURRENT_ACTIVITY = 1500;
CURRENT_ACTIVITY_NOT_SET_VALUE = -9999;
MAX_ATTEMPS_STATUS_UPDATE = 12;
DELAY_BETWEEN_ATTEMPS_STATUS_UPDATE = 2000;
DELAY_TO_UPDATE_STATUS = 800;
DELAY_TO_RELAUNCH_TIMER_ON_NEW_ACTIVITY = 8000;
DELAY_TO_RELAUNCH_TIMER_ON_NEW_COMMAND = 2000;
DELAY_LAUNCH_REFRESH = 2500;

module.exports = {
  DEFAULT_HUB_PORT,
  TIMEOUT_REFRESH_CURRENT_ACTIVITY,
  CURRENT_ACTIVITY_NOT_SET_VALUE,
  MAX_ATTEMPS_STATUS_UPDATE,
  DELAY_BETWEEN_ATTEMPS_STATUS_UPDATE,
  DELAY_TO_UPDATE_STATUS,
  DELAY_TO_RELAUNCH_TIMER_ON_NEW_ACTIVITY,
  DELAY_TO_RELAUNCH_TIMER_ON_NEW_COMMAND,
  DELAY_LAUNCH_REFRESH,
};
